In [1]:
import pandas as pd
import nltk
from nltk.tokenize import wordpunct_tokenize
from nltk.corpus import stopwords
from unidecode import unidecode
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
dados = pd.read_csv("../WebScrapping/20260412_DadosDafiti.csv")

df = pd.DataFrame(dados)

df

,Marca,Cor,Vendedor,Produto,Tags,Preço Original,Preço Pix,Preço Parcelado,Quantidade de Parcelas
0,Jorge Bischoff,Marrom,Dafiti,Bota Feminina Jorge Bischoff Cano Alto Marrom,"Calçados,Calçados Femininos,Botas,Bota Montari...","R$ 1.199,00","R$ 589,99","R$ 627,65",10x
1,Arezzo,Preto,Dafiti,Bota Feminina Arezzo Cano Baixo Preta,"Calçados,Calçados Femininos,Botas,Bota Cano Curto","R$ 599,90","R$ 563,90","R$ 599,89",10x
2,Arezzo,Marrom,Dafiti,Bota Feminina Arezzo Cano Baixo Marrom,"Calçados,Calçados Femininos,Botas,Bota Cano Curto","R$ 599,90","R$ 563,90","R$ 599,89",10x
3,adidas Originals,Marrom,Dafiti,Tênis adidas Originals SL 72 OG Marrom,"Calçados,Calçados Femininos,Tênis,Tênis Casual","R$ 699,99","R$ 657,98","R$ 699,98",10x
4,adidas Originals,Preto,Dafiti,Tênis adidas Originals Superstar Slip On Preto,"Calçados,Calçados Femininos,Tênis,Slip On,Têni...","R$ 399,99","R$ 299,99","R$ 319,14",5x
...,...,...,...,...,...,...,...,...,...
1195,Usaflex,Preto,Dafiti,Sapatilha Feminina Usaflex Couro Preta,"Calçados,Calçados Femininos,Sapatilhas,Sapatil...","R$ 289,99","R$ 149,99","R$ 159,56",2x
1196,Vizzano,Marrom,Dafiti,Rasteira Vizzano Animal Print Marrom,"Calçados,Calçados Femininos,Rasteirinhas","R$ 119,90","R$ 59,99","R$ 63,82",1x
1197,Santa Lolla,Vermelho,Dafiti,Sapatilha Santa Lolla Aplicação Vermelha,"Calçados,Calçados Femininos,Sapatilhas,Sapatil...","R$ 269,90","R$ 169,99","R$ 180,84",3x
1198,VIA UNO,Preto,Dafiti,Mocassim Feminino Via Uno Detalhe Dourado Preto,"Calçados,Calçados Femininos,Mocassim","R$ 129,99","R$ 64,99","R$ 69,14",1x
1199,Santa Lolla,Marrom,Dafiti,Scarpin Feminino Santa Lolla Amarração Marrom,"Calçados,Calçados Femininos,Scarpin","R$ 249,90","R$ 169,99","R$ 180,84",3x

In [3]:

print(f"Antes: {len(df)} produtos")

df = df.drop_duplicates(subset="Produto").reset_index(drop=True)

print(f"Depois: {len(df)} produtos")

df.head()

Antes: 1200 produtos
Depois: 1101 produtos

,Marca,Cor,Vendedor,Produto,Tags,Preço Original,Preço Pix,Preço Parcelado,Quantidade de Parcelas
0,Jorge Bischoff,Marrom,Dafiti,Bota Feminina Jorge Bischoff Cano Alto Marrom,"Calçados,Calçados Femininos,Botas,Bota Montari...","R$ 1.199,00","R$ 589,99","R$ 627,65",10x
1,Arezzo,Preto,Dafiti,Bota Feminina Arezzo Cano Baixo Preta,"Calçados,Calçados Femininos,Botas,Bota Cano Curto","R$ 599,90","R$ 563,90","R$ 599,89",10x
2,Arezzo,Marrom,Dafiti,Bota Feminina Arezzo Cano Baixo Marrom,"Calçados,Calçados Femininos,Botas,Bota Cano Curto","R$ 599,90","R$ 563,90","R$ 599,89",10x
3,adidas Originals,Marrom,Dafiti,Tênis adidas Originals SL 72 OG Marrom,"Calçados,Calçados Femininos,Tênis,Tênis Casual","R$ 699,99","R$ 657,98","R$ 699,98",10x
4,adidas Originals,Preto,Dafiti,Tênis adidas Originals Superstar Slip On Preto,"Calçados,Calçados Femininos,Tênis,Slip On,Têni...","R$ 399,99","R$ 299,99","R$ 319,14",5x

In [3]:
def limpar_texto(texto):
    texto = texto.lower()
    texto = unidecode(texto)
    tokens = wordpunct_tokenize(texto)
    tokens = [token for token in tokens if token.isalnum()]
    return " ".join(tokens)


df["Produto_limpo"] = df["Produto"].apply(limpar_texto)

df[["Produto", "Produto_limpo"]].head()

,Produto,Produto_limpo
0,Bota Feminina Jorge Bischoff Cano Alto Marrom,bota feminina jorge bischoff cano alto marrom
1,Bota Feminina Arezzo Cano Baixo Preta,bota feminina arezzo cano baixo preta
2,Bota Feminina Arezzo Cano Baixo Marrom,bota feminina arezzo cano baixo marrom
3,Tênis adidas Originals SL 72 OG Marrom,tenis adidas originals sl 72 og marrom
4,Tênis adidas Originals Superstar Slip On Preto,tenis adidas originals superstar slip on preto

In [4]:
nltk.download("stopwords", quiet=True)

stopwords_pt = stopwords.words("portuguese")
stopwords_pt = [unidecode(palavra) for palavra in stopwords_pt]
stopwords_pt = set(stopwords_pt)


def remover_stopwords(texto):
    tokens = texto.split()
    tokens = [token for token in tokens if token not in stopwords_pt]
    return tokens


df["tokens_sem_stopwords"] = df["Produto_limpo"].apply(remover_stopwords)
df["Produto_sem_stopwords"] = df["tokens_sem_stopwords"].str.join(" ")

df[["Produto_limpo", "tokens_sem_stopwords", "Produto_sem_stopwords"]].head()

,Produto_limpo,tokens_sem_stopwords,Produto_sem_stopwords
0,bota feminina jorge bischoff cano alto marrom,"[bota, feminina, jorge, bischoff, cano, alto, ...",bota feminina jorge bischoff cano alto marrom
1,bota feminina arezzo cano baixo preta,"[bota, feminina, arezzo, cano, baixo, preta]",bota feminina arezzo cano baixo preta
2,bota feminina arezzo cano baixo marrom,"[bota, feminina, arezzo, cano, baixo, marrom]",bota feminina arezzo cano baixo marrom
3,tenis adidas originals sl 72 og marrom,"[tenis, adidas, originals, sl, 72, og, marrom]",tenis adidas originals sl 72 og marrom
4,tenis adidas originals superstar slip on preto,"[tenis, adidas, originals, superstar, slip, on...",tenis adidas originals superstar slip on preto

In [5]:
vectorizer = CountVectorizer()
matriz_bow = vectorizer.fit_transform(df["Produto_sem_stopwords"])

df_bow = pd.DataFrame(
    matriz_bow.toarray(),
    columns=vectorizer.get_feature_names_out()
)

df_bow.head()

,1080,11,1130,28,2k,3cm,480,530,6cm,72,...,vicenza,vinho,vintage,vizzano,warm,wh,white,wm,xl,ziper
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
colunas_com_numeros = [col for col in df_bow.columns if any(char.isdigit() for char in col)]

df_bow = df_bow.drop(columns=colunas_com_numeros)

print(f"{len(colunas_com_numeros)} colunas removidas")
df_bow.head()

12 colunas removidas

,aberta,ad,adidas,adistar,adorno,agulha,aju,ajuste,al,alca,...,vicenza,vinho,vintage,vizzano,warm,wh,white,wm,xl,ziper
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
metadados = df[["Marca", "Cor", "Vendedor", "Produto", "Tags", "Preço Original", "Preço Pix", "Preço Parcelado", "Quantidade de Parcelas"]].reset_index(drop=True)
bow_com_prefixo = df_bow.add_prefix("bow_").reset_index(drop=True)

df_final = pd.concat([metadados, bow_com_prefixo], axis=1)

df_final.head()

,Marca,Cor,Vendedor,Produto,Tags,Preço Original,Preço Pix,Preço Parcelado,Quantidade de Parcelas,bow_aberta,...,bow_vicenza,bow_vinho,bow_vintage,bow_vizzano,bow_warm,bow_wh,bow_white,bow_wm,bow_xl,bow_ziper
0,Jorge Bischoff,Marrom,Dafiti,Bota Feminina Jorge Bischoff Cano Alto Marrom,"Calçados,Calçados Femininos,Botas,Bota Montari...","R$ 1.199,00","R$ 589,99","R$ 627,65",10x,0,...,0,0,0,0,0,0,0,0,0,0
1,Arezzo,Preto,Dafiti,Bota Feminina Arezzo Cano Baixo Preta,"Calçados,Calçados Femininos,Botas,Bota Cano Curto","R$ 599,90","R$ 563,90","R$ 599,89",10x,0,...,0,0,0,0,0,0,0,0,0,0
2,Arezzo,Marrom,Dafiti,Bota Feminina Arezzo Cano Baixo Marrom,"Calçados,Calçados Femininos,Botas,Bota Cano Curto","R$ 599,90","R$ 563,90","R$ 599,89",10x,0,...,0,0,0,0,0,0,0,0,0,0
3,adidas Originals,Marrom,Dafiti,Tênis adidas Originals SL 72 OG Marrom,"Calçados,Calçados Femininos,Tênis,Tênis Casual","R$ 699,99","R$ 657,98","R$ 699,98",10x,0,...,0,0,0,0,0,0,0,0,0,0
4,adidas Originals,Preto,Dafiti,Tênis adidas Originals Superstar Slip On Preto,"Calçados,Calçados Femininos,Tênis,Slip On,Têni...","R$ 399,99","R$ 299,99","R$ 319,14",5x,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
df_final.to_csv('20260421_DadosDafiti_NLP.csv', index=False)

In [9]:
colunas_bow = [coluna for coluna in df_final.columns if coluna.startswith("bow_")]

frequencia_palavras = df_final[colunas_bow].sum().sort_values(ascending=False)

print(f"Total de palavras diferentes: {len(frequencia_palavras)}")

frequencia_palavras.head(10)

Total de palavras diferentes: 456

bow_feminina    491
bow_feminino    304
bow_salto       265
bow_sandalia    265
bow_tenis       261
bow_marrom      182
bow_scarpin     170
bow_preta       159
bow_vizzano     156
bow_rasteira    151
dtype: int64

In [10]:
frequencia_palavras.tail(10)

bow_tranca        1
bow_tramadas      1
bow_ultrarange    1
bow_ua            1
bow_aju           1
bow_an            1
bow_tran          1
bow_urban         1
bow_wh            1
bow_adistar       1
dtype: int64

In [11]:
documentos_por_palavra = (df_final[colunas_bow] > 0).sum().sort_values(ascending=False)
documentos_por_palavra.index = documentos_por_palavra.index.str.replace("bow_", "", regex=False)

documentos_por_palavra.head(10)

feminina    491
feminino    304
salto       265
sandalia    265
tenis       261
marrom      182
scarpin     170
preta       159
vizzano     156
rasteira    151
dtype: int64

In [13]:
df_final["palavras_unicas"] = (df_final[colunas_bow] > 0).sum(axis=1)

df_final[["Produto", "palavras_unicas"]].sort_values("palavras_unicas", ascending=True).head(10)

                                 Produto  palavras_unicas
25                   Tênis Vizzano Preto                3
6     Sandália Melissa Possession Marrom                4
1164  Tamanco Vizzano Aplicação Caramelo                4
44             Scarpin Vizzano Liso Bege                4
508                Rasteira Via Uno Bege                4
511           Rasteira Vizzano Lisa Rosa                4
425          Tênis Puma Palermo Vermelho                4
1166          Bota Bottero Camurça Preta                4
527              Tênis Puma Palermo Rosa                4
496        Tênis ANACAPRI Recorte Branco                4